services:
  webapplication1:
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    depends_on:
      - icecreamapi
    ports:
      - 5000:8080
        
  icecreamapi:
    build:
      context: .
      dockerfile: IceCreamApi/Dockerfile
#    environment:
#      ASPNETCORE_HTTP_PORTS: 80
  
  razorwebapp:
    build:
      context: .
      dockerfile: RazorWebApp/Dockerfile
    depends_on: 
      - icecreamapi
    ports:
      - 5001:8080
    environment:
        ClientAddresses__IceCreamApi: "http://icecreamapi:8080"