services:
  webapplication1:
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    depends_on:
      - icecreamapi
        
  icecreamapi:
    build:
      context: .
      dockerfile: IceCreamApi/Dockerfile
  
  razorwebapp:
    build:
      context: .
      dockerfile: RazorWebApp/Dockerfile
    depends_on: 
      - icecreamapi